### ISSUE TITLE
Slow when undoing

### ISSUE THREAD

**Issue by kristijanhusak** [manasthakur/vim-commentor#3]
Hi,

I noticed that undoing comments of many number of lines (~1k), neovim freezes for some time (5 - 10 seconds). I assume similar happens in vim also. This is also an issue in all comment plugins that i tried (tpope commentary, nerdcommenter), but i'm reporting it here because this one works the best of all those, and it's small. Do you have idea why is undo so slow in that case? Uncommenting manually works great, just the undo freezes.

**Comment by manasthakur** [comment]
Hi @kristijanhusak!

My guess is that it would happen because the state has to be restored from the undo list. While uncommenting manually, it's essentially a new change in the file, which is probably lighter.

However, I do not find any noticeable freeze in Vim version 8.0.642 on my machine while undoing the comment over a block of 2000-3000 lines in a C++ file. Can you please check in Vim once? In case it happens there as well, the reason could also be some syntax-related plugin in your config. Please also check by disabling other plugins and with an empty vimrc.

Regards,
Manas

**Comment by kristijanhusak** [comment]
@manasthakur Yeah, you are right, it's syntax related. When i did `syntax off` it does undo immediately. Thanks.
